version: '3.9'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db_mysql_desafio
    restart: always
    tty: true
    volumes:
      - db_mysql_desafio:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
      - node_network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -hlocalhost -uroot -proot || exit 1']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  node:
    build:
      context: ./node
    container_name: node_app
    networks:
      - node_network
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ['/bin/sh', '-c', 'npm install && npm start']
    volumes:
      - ./node:/usr/src/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

volumes:
  db_mysql_desafio:

networks:
  node_network:
    driver: bridge
